[package]
name = "core-blockchain-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "1.3.3"
rand = "0.9.2"
ring = "0.17.14"
serde = { version = "1.0.226", features = ["derive"] }
serde_json = "1.0.145"
sha2 = "0.10.9"
thiserror = "2.0.16"
